#include "fdfgenerator.h"
#include "elements/uielementdata.h"

#include <QFile>
#include <QFileInfo>
#include <QMap>
#include <QSet>
#include <QDebug>

FdfGenerator::FdfGenerator(QObject *parent)
    : QObject(parent)
{
}

QString FdfGenerator::escapeString(const QString &s)
{
    QString escaped = s;
    escaped.replace("\\", "\\\\");
    escaped.replace("\"", "\\\"");
    return escaped;
}

QString FdfGenerator::makeTextureRef(const QString &texture)
{
    // If the path is absolute (contains a drive letter or starts with /),
    // extract just the filename — War3 FDF expects relative paths
    QFileInfo fi(texture);
    if (fi.isAbsolute()) {
        return fi.fileName();
    }

    QString ref = texture;
    if (ref.contains("textures/") || ref.contains("textures\\")) {
        int idx = ref.indexOf("textures");
        if (idx >= 0) {
            ref = "war3mapUI\\" + ref.mid(idx);
        }
    }
    ref.replace('/', '\\');
    return ref;
}

bool FdfGenerator::exportFdf(const QList<UiElementData> &elements,
                              const QString &outputPath,
                              bool war3Mode,
                              QString *errorMsg)
{
    QMap<QString, UiElementData> dataMap;
    for (const auto &el : elements) {
        dataMap[el.name] = el;
    }

    QSet<QString> written;
    QString output;

    // Header comment + include
    output = "// Generated by War3UiBuilder\n\n";
    output += "Include \"UI\\\\FrameDef\\\\UI\\\\FrameDef.toc\",\n\n";

    // Find root elements (no parent) and write them recursively
    for (const auto &el : elements) {
        if (el.parent.isEmpty() || !dataMap.contains(el.parent)) {
            writeElement(output, el, dataMap, written, 1, war3Mode);
            // Remove trailing comma from last root element's closing brace
            // (the writeElement already adds a comma after each child block)
        }
    }

    // Write any remaining elements not yet written (orphans)
    for (const auto &el : elements) {
        if (!written.contains(el.name)) {
            writeElement(output, el, dataMap, written, 1, war3Mode);
        }
    }

    QFile file(outputPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (errorMsg)
            *errorMsg = QString("Cannot write to file: %1").arg(outputPath);
        qWarning() << "Failed to write FDF:" << outputPath;
        return false;
    }
    file.write(output.toUtf8());
    file.close();
    return true;
}

// Helper to convert element type to FDF uppercase string
static QString fdfTypeFor(const QString &type)
{
    if (type == "SIMPLEFRAME") return "SIMPLEFRAME";
    if (type == "BACKDROP")    return "BACKDROP";
    if (type == "FRAME")       return "FRAME";
    if (type == "TEXT")        return "TEXT";
    if (type == "BUTTON")      return "BUTTON";
    if (type == "EDITBOX")     return "EDITBOX";
    if (type == "SLIDER")      return "SLIDER";
    return "SIMPLEFRAME";
}

// Check if an identifier is a known FDF frame type keyword
static bool isFrameType(const QString &s)
{
    return s == "SIMPLEFRAME" || s == "BACKDROP" || s == "FRAME"
        || s == "TEXT" || s == "BUTTON" || s == "EDITBOX"
        || s == "SLIDER" || s == "GLUEBUTTON" || s == "SPRITE"
        || s == "POPUPMENU" || s == "LISTBOX" || s == "SCROLLBAR";
}

void FdfGenerator::writeElement(QString &output, const UiElementData &element,
                                 const QMap<QString, UiElementData> &dataMap,
                                 QSet<QString> &written,
                                 int indent, bool war3Mode) const
{
    if (written.contains(element.name)) return;
    written.insert(element.name);

    QString ind(indent * 4, ' ');

    // Calculate parent-relative coordinates in pixel space
    double relX = element.x;
    double relY = element.y;
    if (!element.parent.isEmpty() && dataMap.contains(element.parent)) {
        const auto &parent = dataMap[element.parent];
        relX -= parent.x;
        relY -= parent.y;
    }

    // Frame block header — use type as keyword (e.g. BACKDROP "Name")
    output += QString("%1%2 \"%3\" {\n").arg(ind, fdfTypeFor(element.type), escapeString(element.name));

    if (war3Mode) {
        output += QString("%1    Width %2,\n").arg(ind).arg(element.width / 1920.0 * 0.8, 0, 'f', 4);
        output += QString("%1    Height %2,\n").arg(ind).arg(element.height / 1080.0 * 0.6, 0, 'f', 4);
    } else {
        output += QString("%1    Width %2,\n").arg(ind).arg(element.width, 0, 'f', 1);
        output += QString("%1    Height %2,\n").arg(ind).arg(element.height, 0, 'f', 1);
    }

    // SetPoint replaces X/Y/Anchor
    {
        QString target;
        if (!element.parent.isEmpty() && dataMap.contains(element.parent))
            target = escapeString(element.parent);
        else
            target = "Parent";
        if (war3Mode) {
            double sX = relX / 1920.0 * 0.8;
            double sY = -relY / 1080.0 * 0.6;
            output += QString("%1    SetPoint \"TOPLEFT\", \"%2\", \"TOPLEFT\", %3, %4,\n")
                .arg(ind).arg(target).arg(sX, 0, 'f', 4).arg(sY, 0, 'f', 4);
        } else {
            output += QString("%1    SetPoint \"TOPLEFT\", \"%2\", \"TOPLEFT\", %3, %4,\n")
                .arg(ind).arg(target).arg(relX, 0, 'f', 1).arg(relY, 0, 'f', 1);
        }
    }

    // Texture
    if (element.hasTexture && !element.texture.isEmpty()) {
        output += QString("%1    Texture \"%2\",\n").arg(ind, makeTextureRef(element.texture));
    }

    // Type-specific properties
    if (element.type == "BUTTON") {
        if (!element.normalTexture.isEmpty())
            output += QString("%1    NormalTexture \"%2\",\n").arg(ind, makeTextureRef(element.normalTexture));
        if (!element.highlightTexture.isEmpty())
            output += QString("%1    HighlightTexture \"%2\",\n").arg(ind, makeTextureRef(element.highlightTexture));
    } else if (element.type == "MODEL") {
        if (!element.modelPath.isEmpty())
            output += QString("%1    Model \"%2\",\n").arg(ind, escapeString(element.modelPath));
    } else if (element.type == "TEXT") {
        if (!element.textContent.isEmpty())
            output += QString("%1    Text \"%2\",\n").arg(ind, escapeString(element.textContent));
        if (element.fontSize > 0)
            output += QString("%1    FontSize %2,\n").arg(ind).arg(element.fontSize, 0, 'f', 0);
        if (!element.textColor.isEmpty())
            output += QString("%1    TextColor \"%2\",\n").arg(ind, element.textColor);
    }

    // Extended properties
    for (auto it = element.properties.begin(); it != element.properties.end(); ++it) {
        output += QString("%1    %2 \"%3\",\n").arg(ind, it.key(), escapeString(it.value()));
    }

    // Write children recursively
    for (auto it = dataMap.constBegin(); it != dataMap.constEnd(); ++it) {
        if (!written.contains(it.key()) && it.value().parent == element.name) {
            writeElement(output, it.value(), dataMap, written, indent + 1, war3Mode);
        }
    }

    // Close block
    output += QString("%1},\n").arg(ind);
}

// ── FDF Parser ──

FdfGenerator::FdfParser::FdfParser(const QString &source)
    : m_source(source), m_pos(0)
{
}

void FdfGenerator::FdfParser::skipWhitespaceAndComments()
{
    while (m_pos < m_source.size()) {
        QChar ch = m_source.at(m_pos);
        if (ch.isSpace()) {
            ++m_pos;
            continue;
        }
        // Single-line comment: //
        if (ch == '/' && m_pos + 1 < m_source.size() && m_source.at(m_pos + 1) == '/') {
            while (m_pos < m_source.size() && m_source.at(m_pos) != '\n')
                ++m_pos;
            continue;
        }
        // Multi-line comment: /* ... */
        if (ch == '/' && m_pos + 1 < m_source.size() && m_source.at(m_pos + 1) == '*') {
            m_pos += 2;
            while (m_pos + 1 < m_source.size() &&
                   !(m_source.at(m_pos) == '*' && m_source.at(m_pos + 1) == '/'))
                ++m_pos;
            if (m_pos + 1 < m_source.size()) m_pos += 2;
            continue;
        }
        break;
    }
}

FdfGenerator::FdfToken FdfGenerator::FdfParser::nextToken()
{
    if (m_hasPeeked) {
        m_hasPeeked = false;
        return m_peeked;
    }

    skipWhitespaceAndComments();

    if (m_pos >= m_source.size())
        return { FdfToken::Eof, "" };

    QChar ch = m_source.at(m_pos);

    // Single-character tokens
    if (ch == '{') { ++m_pos; return { FdfToken::BlockStart, "{" }; }
    if (ch == '}') { ++m_pos; return { FdfToken::BlockEnd, "}" }; }
    if (ch == ',') { ++m_pos; return { FdfToken::Comma, "," }; }
    if (ch == ';') { ++m_pos; return { FdfToken::Semicolon, ";" }; }
    if (ch == '=') { ++m_pos; return { FdfToken::Equals, "=" }; }

    // String literal
    if (ch == '"') {
        ++m_pos; // skip opening quote
        QString value;
        while (m_pos < m_source.size()) {
            QChar c = m_source.at(m_pos);
            if (c == '\\' && m_pos + 1 < m_source.size()) {
                ++m_pos;
                QChar next = m_source.at(m_pos);
                if (next == '"') value += '"';
                else if (next == '\\') value += '\\';
                else if (next == 'n') value += '\n';
                else if (next == 't') value += '\t';
                else value += next;
                ++m_pos;
            } else if (c == '"') {
                ++m_pos; // skip closing quote
                break;
            } else {
                value += c;
                ++m_pos;
            }
        }
        return { FdfToken::String, value };
    }

    // Identifier (keyword or number)
    int start = m_pos;
    while (m_pos < m_source.size()) {
        QChar c = m_source.at(m_pos);
        if (c.isLetterOrNumber() || c == '_' || c == '.' || c == '-' || c == '+' || c == '#')
            ++m_pos;
        else
            break;
    }
    if (m_pos > start) {
        return { FdfToken::Identifier, m_source.mid(start, m_pos - start) };
    }

    // Unexpected character — skip and return identifier
    ++m_pos;
    return { FdfToken::Identifier, QString(ch) };
}

FdfGenerator::FdfToken FdfGenerator::FdfParser::peekToken()
{
    if (!m_hasPeeked) {
        m_peeked = nextToken();
        m_hasPeeked = true;
    }
    return m_peeked;
}

void FdfGenerator::FdfParser::consumeToken()
{
    if (m_hasPeeked) {
        m_hasPeeked = false;
    } else {
        nextToken();
    }
}

static void applyProperty(UiElementData &element, const QString &key,
                           const QString &strValue, double numValue)
{
    if (key == "Type") {
        element.type = strValue.toUpper();
    } else if (key == "Width") {
        element.width = numValue;
    } else if (key == "Height") {
        element.height = numValue;
    } else if (key == "X") {
        element.x = numValue;
    } else if (key == "Y") {
        element.y = numValue;
    } else if (key == "Texture") {
        element.texture = strValue;
        element.hasTexture = true;
    } else if (key == "NormalTexture") {
        element.normalTexture = strValue;
    } else if (key == "HighlightTexture") {
        element.highlightTexture = strValue;
    } else if (key == "Model") {
        element.modelPath = strValue;
    } else if (key == "Text") {
        element.textContent = strValue;
    } else if (key == "FontSize") {
        element.fontSize = numValue;
    } else if (key == "TextColor") {
        element.textColor = strValue;
    } else {
        // Extended properties
        element.properties[key] = strValue;
    }
}

// Parse a single Frame block from the FDF — returns a populated UiElementData
// Nested Frame children are appended directly to @p result with parent set.
UiElementData FdfGenerator::parseFrameBlock(FdfParser &parser,
                                              QList<UiElementData> &result,
                                              const QString &frameType)
{
    // Next token should be a string (frame name)
    FdfToken nameToken = parser.nextToken();
    UiElementData element;
    if (nameToken.type == FdfGenerator::FdfToken::String)
        element.name = nameToken.value;
    if (!frameType.isEmpty())
        element.type = frameType;
    element.width = 100.0;
    element.height = 100.0;

    // Next should be '{'
    FdfGenerator::FdfToken openToken = parser.nextToken();
    if (openToken.type != FdfGenerator::FdfToken::BlockStart)
        return element;

    // Parse block content until '}'
    while (true) {
        FdfGenerator::FdfToken keyToken = parser.nextToken();
        if (keyToken.type == FdfGenerator::FdfToken::BlockEnd)
            break;  // End of this frame block
        if (keyToken.type == FdfGenerator::FdfToken::Eof)
            break;

        // Check for nested frame (either "Frame" keyword or type keyword)
        if (keyToken.type == FdfGenerator::FdfToken::Identifier &&
            (keyToken.value == "Frame" || isFrameType(keyToken.value))) {
            // Recursively parse child frame
            QString kw = keyToken.value;
            UiElementData child = parseFrameBlock(parser, result,
                isFrameType(kw) ? kw : QString());
            child.parent = element.name;
            result.append(child);
            continue;
        }

        if (keyToken.type != FdfGenerator::FdfToken::Identifier)
            continue;

        QString key = keyToken.value;
        FdfGenerator::FdfToken valueToken = parser.nextToken();

        // Skip '=' if present
        if (valueToken.type == FdfGenerator::FdfToken::Equals)
            valueToken = parser.nextToken();

        QString strValue;
        double numValue = 0;

        if (valueToken.type == FdfGenerator::FdfToken::String) {
            strValue = valueToken.value;
        } else if (valueToken.type == FdfGenerator::FdfToken::Identifier) {
            strValue = valueToken.value;
            bool ok;
            numValue = valueToken.value.toDouble(&ok);
        }

        // Skip comma or semicolon after value
        FdfGenerator::FdfToken after = parser.peekToken();
        if (after.type == FdfGenerator::FdfToken::Comma ||
            after.type == FdfGenerator::FdfToken::Semicolon)
            parser.consumeToken();

        applyProperty(element, key, strValue, numValue);
    }

    return element;
}

QList<UiElementData> FdfGenerator::importFdf(const QString &filePath, QString *errorMsg)
{
    QList<UiElementData> result;

    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        if (errorMsg) *errorMsg = QString("Cannot open file: %1").arg(filePath);
        return result;
    }

    QString source = QString::fromUtf8(file.readAll());
    file.close();

    FdfParser parser(source);
    FdfToken token = parser.nextToken();

    // Scan for frame declarations at the top level
    while (token.type != FdfToken::Eof) {
        if (token.type == FdfToken::Identifier &&
            (token.value == "Frame" || isFrameType(token.value))) {
            QString kw = token.value;
            // For type-keyword declarations (e.g. BACKDROP "Name"), pass type;
            // for "Frame" keyword, type comes from inside the block
            UiElementData element = parseFrameBlock(parser, result,
                isFrameType(kw) ? kw : QString());
            if (!element.name.isEmpty()) {
                result.append(element);
            }
        }
        token = parser.nextToken();
    }

    // Convert War3 normalized coordinates back to pixels if needed
    // (Heuristic: if values are in 0-0.8 / 0-0.6 range, assume War3 mode)
    bool war3Mode = false;
    if (!result.isEmpty()) {
        int war3Count = 0;
        for (const auto &el : result) {
            if (el.x < 1.0 && el.x > -1.0 &&
                el.y < 1.0 && el.y > -1.0 &&
                el.width < 1.0 && el.height < 1.0) {
                ++war3Count;
            }
        }
        war3Mode = (war3Count > result.size() / 2);
    }

    if (war3Mode) {
        for (auto &el : result) {
            el.x = el.x / 0.8 * 1920.0;
            el.y = -(el.y / 0.6 * 1080.0);
            el.width = el.width / 0.8 * 1920.0;
            el.height = el.height / 0.6 * 1080.0;
        }
    }

    return result;
}
