#include <QtTest>
#include <QJsonObject>
#include "../elements/uielementdata.h"

// ── Coordinate conversion (mirrors IniGenerator logic) ──
static double war3X(double relPx)  { return relPx / 1920.0 * 0.8; }
static double war3Y(double relPx)  { return -relPx / 1080.0 * 0.6; }
static double war3W(double pw)     { return pw / 1920.0 * 0.8; }
static double war3H(double ph)     { return ph / 1080.0 * 0.6; }

// ── Cycle detection (mirrors UiScene::wouldCreateCycle) ──
static bool wouldCreateCycle(const QMap<QString, QString> &parents,
                             const QString &childName,
                             const QString &potentialParent)
{
    if (childName == potentialParent) return true;
    QString current = potentialParent;
    while (!current.isEmpty()) {
        if (current == childName) return true;
        if (!parents.contains(current)) break;
        current = parents[current];
    }
    return false;
}

class TestWar3UiBuilder : public QObject
{
    Q_OBJECT

private slots:
    // ── Coord Tests ──
    void testWar3X()
    {
        QCOMPARE(war3X(0.0), 0.0);
        QCOMPARE(war3X(960.0), 0.4);
        QCOMPARE(war3X(1920.0), 0.8);
    }

    void testWar3Y()
    {
        QCOMPARE(war3Y(0.0), 0.0);
        QCOMPARE(war3Y(100.0), -100.0 / 1080.0 * 0.6);
        QCOMPARE(war3Y(-100.0), 100.0 / 1080.0 * 0.6);
    }

    void testWar3WH()
    {
        QCOMPARE(war3W(100.0), 100.0 / 1920.0 * 0.8);
        QCOMPARE(war3H(100.0), 100.0 / 1080.0 * 0.6);
        QCOMPARE(war3W(1920.0), 0.8);
        QCOMPARE(war3H(1080.0), 0.6);
    }

    // ── Serialization Tests ──
    void testRoundTrip()
    {
        UiElementData el;
        el.name = "TestButton";
        el.type = "BUTTON";
        el.x = 100.0; el.y = 200.0;
        el.width = 300.0; el.height = 50.0;
        el.parent = "Root";
        el.hasTexture = true;
        el.texture = "textures/btn.dds";
        el.textContent = "Click Me";
        el.fontSize = 16.0;
        el.textColor = "#FF0000";

        QJsonObject obj;
        obj["name"] = el.name;
        obj["type"] = el.type;
        obj["x"] = el.x; obj["y"] = el.y;
        obj["width"] = el.width; obj["height"] = el.height;
        obj["parent"] = el.parent;
        obj["hasTexture"] = el.hasTexture;
        obj["texture"] = el.texture;
        obj["textContent"] = el.textContent;
        obj["fontSize"] = el.fontSize;
        obj["textColor"] = el.textColor;

        UiElementData el2;
        el2.name = obj["name"].toString();
        el2.type = obj["type"].toString();
        el2.x = obj["x"].toDouble();
        el2.y = obj["y"].toDouble();
        el2.width = obj["width"].toDouble();
        el2.height = obj["height"].toDouble();
        el2.parent = obj["parent"].toString();
        el2.hasTexture = obj["hasTexture"].toBool();
        el2.texture = obj["texture"].toString();
        el2.textContent = obj["textContent"].toString();
        el2.fontSize = obj["fontSize"].toDouble();
        el2.textColor = obj["textColor"].toString();

        QCOMPARE(el2.name, el.name);
        QCOMPARE(el2.type, el.type);
        QCOMPARE(el2.x, el.x);
        QCOMPARE(el2.y, el.y);
        QCOMPARE(el2.parent, el.parent);
        QCOMPARE(el2.textContent, el.textContent);
    }

    void testIsValid()
    {
        UiElementData empty;
        QVERIFY(!empty.isValid());

        UiElementData valid;
        valid.name = "Foo";
        QVERIFY(valid.isValid());
    }

    // ── Cycle Detection Tests ──
    void testSelfParent()
    {
        QMap<QString, QString> parents{{"A", ""}};
        QVERIFY(wouldCreateCycle(parents, "A", "A"));
    }

    void testSimpleCycle()
    {
        QMap<QString, QString> parents{{"A", ""}, {"B", "A"}};
        QVERIFY(wouldCreateCycle(parents, "A", "B"));
    }

    void testNoCycle()
    {
        QMap<QString, QString> parents{{"A", ""}, {"B", ""}};
        QVERIFY(!wouldCreateCycle(parents, "A", "B"));
    }

    void testDeepNoCycle()
    {
        QMap<QString, QString> parents{{"A", ""}, {"B", "A"}, {"C", "B"}};
        QVERIFY(!wouldCreateCycle(parents, "C", "A"));
        QVERIFY(wouldCreateCycle(parents, "A", "C"));
    }

    void testUnknownParent()
    {
        QMap<QString, QString> parents{{"A", ""}};
        QVERIFY(!wouldCreateCycle(parents, "A", "UNKNOWN"));
    }
};

// Manual main — .moc must be generated by MOC and included here
int main(int argc, char *argv[])
{
    TestWar3UiBuilder test;
    return QTest::qExec(&test, argc, argv);
}

#include "test_coord.moc"
